# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ThinkData
tagline:          'All things data'
description:      'Data Science'
url:              http://thinkdata.be
baseurl:          /
logo :            http://static.tumblr.com/442182ab6d03cbbc9bee606ced985d94/oszfyit/CaCmhskd7/tumblr_static_logo.png
author:
  name:           'Kenny Helsens'
  url:            https://twitter.com/kennyhelsens

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kennyhelsens

url:
  linkedin:       https://www.linkedin.com/profile/view?id=17990438
  twitter:        https://twitter.com/kennyhelsens
name: ThinkData Blog
description: ThinkData Blog
url: http://thinkdata.be

redcarpet:
  extensions:
    ["no_intra_emphasis","autolink","tables","with_toc_data"]
